### ISSUE TITLE
Already running a full ergo node, do I need Docker steps?

### ISSUE THREAD

**Issue by TheStophe** [reqlez/tn-ergo-easy-oracle#1]
Do I need to follow the Docker container steps if i'm already running a full node on the raspberry pi ARM? Is there a step to skip to? Perhaps this can be clarified in the guide for novices.

**Comment by reqlez** [comment]
You could just build a service for the binary here: https://github.com/ergoplatform/oracle-core/releases/download/v2.0.0/oracle-core-v2.0.0-aarch64-unknown-linux-gnu.tar.gz

This is just easier to manage and get started. I personally use this setup so that means it's also tested.

Another thing you could do, is re-use your existing data directory and make the docker setup use your existing config / data folders by putting them in the right place.

Yet another alternative is comment out the node part of the docker-compose file, and point this to your existing node:
https://github.com/reqlez/ergo-easy-oracle/blob/main/oracle_data/oracle_config.yaml#L1 then replace that with: http://host.docker.internal  but this only works if you add this to docker-compose i believe:
```
    network_mode: bridge
    extra_hosts:
        - "host.docker.internal:host-gateway"

```

**Comment by TheStophe** [comment]
Thank you! I apologize have not given this a try yet.

So if I use your ergo-easy-oracle guide will it download another full node? I guess that's what i'm trying to avoid. I may try and do the first option and use your config files as guidance perhaps. Will certainly just use your docker image for the next go-around.

**Comment by reqlez** [comment]
confirmed @ccgarant oracle is operational now.
